<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Domain\Domain.csproj" />
      <ProjectReference Include="..\Repository\Repository.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MailKit" Version="4.18.1" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.12" />
      <PackageReference Include="Quartz" Version="4.3.0" />
    </ItemGroup>

</Project>
